### ISSUE TITLE
Provide a "test" for variables before actually generating configuration

### ISSUE THREAD

**Issue by lenards** [cyverse/clank#105]
The `./configure` script in Atmosphere, Troposphere, & Atmosphere-Ansible has a [`--dry-run`](https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/master/configure#L581-L594) flag that could be used by Clank to allow for _check_.

**Comment by steve-gregory** [comment]
@lenards does --debug take care of your need? It should show how all variables have been evaluated prior to execution of the playbooks...

**Comment by lenards** [comment]
I think the intent of this was to provide "fail-fast" feedback on the variables. So, you _would_ know if the variables + template merge is going to succeed prior to running clank.

**Comment by lenards** [comment]
I think `--debug` still puts the burden on the operator to visually review and validate the variables, what I was offering was noting that `./configure` has a flag to off-load this to the script.

**Comment by lenards** [comment]
This could be closed as feedback accepted and _noted_. It's not critical.
