### ISSUE TITLE
Update Pip and Virtualenv

### ISSUE THREAD

**Issue by amercer1** [cyverse/clank#106]
```
pip install -U pip virtualenv
but for one, system-python having the highest level of pip/virtualenv (nothing wrong with that)
and making sure that individual virtualenvs like /opt/env/[troposphere,atmo]
have latest probably also good its minor-priority
```
- @steve-gregory

**Comment by lenards** [comment]
I think it is important to add that we do *not* want `-U` to apply to the requirements files for the application. However, we *do* want to ensure that `pip` and `virtualenv` are the latest versions and not the version distributed with a given Linux distribution we are targeting for installation.
