### ISSUE TITLE
Improve variable combined cert vars

### ISSUE THREAD

**Issue by cdosborn** [cyverse/clank#107]
We have these two vars, the first is not being used (except in a task name) and the second bucks our current conventions of having `*_PATH` be a dir like with `KEY_PATH`,`THEME_PATH`, and so on. 

```
COMBINED_CERT_FILE:
COMBINED_CERT_PATH:
```

**Comment by lenards** [comment]
I agree Connor. Thanks for noting this. 

The `nginx` and `uwsgi.ini` sections of variables will be re-worked this coming sprint.

**Comment by lenards** [comment]
I am adding this to the v2.1 milestone and accepting the issue as assigned to me.

**Comment by lenards** [comment]
This effort will be related to #42.

**Comment by lenards** [comment]
(R.I.P. _Ratchet_)

**Comment by cdosborn** [comment]
👍

**Comment by lenards** [comment]
I think this is something that Steve might be working toward. Clearing my assignment.

**Comment by steve-gregory** [comment]
I believe this is no longer a problem -- @cdosborn can you confirm?

**Comment by cdosborn** [comment]
This is what tripped me up when I was configuring:
```
COMBINED_CERT_FILE = self_signed_combined.crt
COMBINED_CERT_PATH = /etc/ssl/certs/self_signed_combined.crt
KEY_FILE = self-signed.key
KEY_PATH = /etc/ssl/private
```
The combined cert path includes the cert file. I'm not sure why we want both to be configurable.

**Comment by steve-gregory** [comment]
Ahh, Okay I see what you mean now. Yeah the format i'd rather see here is:
```
COMBINED_CERT_FILE = self_signed_combined.crt
COMBINED_CERT_DIR = /etc/ssl/certs
COMBINED_CERT_PATH = "{{COMBINED_CERT_DIR}}/{{COMBINED_CERT_FILE}}"
...
```
Thanks for the clarification!

**Comment by lenards** [comment]
I would love it if we have a convention for `..._FILE`, `..._DIR`, `..._PATH`.
