### ISSUE TITLE
app-load-data-postgres role doesn't work if replacing an existing database

### ISSUE THREAD

**Issue by c-mart** [cyverse/clank#117]
If there is already an atmo_prod database on the target server, and the deployer wishes for Clank to load a new database from a dump file, the existing database must be dropped first. Clank should do this but it does not.

To avoid the possibility of losing important data, Clank could either take a backup of the existing database before dropping it, or prompt to confirm that the old database will be dropped (see #62).

**Comment by steve-gregory** [comment]
How to restore the entire psql cluster (all databases restore procedure):
```PG_VERSION=9.6
pg_dropcluster $PG_VERSION main --stop
pg_createcluster $PG_VERSION main
pg_ctlcluster $PG_VERSION main start
pg_restore -f backups/path/to/dump/file.sql
<Wait.. Full database restores take considerable amount of time>```

Goes without saying, use this command at your own risk.
