### ISSUE TITLE
URL update in Readme

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#143]
The URL in the readme for cloning clank needs to be updated 💯 

Thanks!

**Comment by lenards** [comment]
@xuhang57 - I updated the URL in the README. 

If you have an existing checkout of `clank`, you can update the remote url like so:
```
git remote set-url origin git@github.com:cyverse/clank.git
```

**Comment by lenards** [comment]
If this is _not_ a resolution, please let us know and we're fix ASAP.
