### ISSUE TITLE
Issues of running 'pip install -r clank/requirements.txt'

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#179]
Currently, when you run `pip install -r clank/requirements.txt`, you need to:

`pip install -U pip`
`pip install six`
`pip install packaging`
`pip install appdirs` (not sure whether this is the correct package name)

And after this, `pip install -r clank/requirements.txt` would work and let you move forward.

To reproduce this, just follow the ReadMe.md until `pip install -r clank/requirements.txt` and you should be able to see failures of `pip install`.

@steve-gregory 

Thanks
Lucas

**Comment by cdosborn** [comment]
Would you happen to know what your pip version was prior to upgrading? I think its worth including in the README.md that pip/virtualenv should be a recent version

**Comment by xuhang57** [comment]
Sorry I don't. But I think the version of pip in the Ubuntu 14.04 repositories is only 1.5.4. I could check it tomorrow.  

Thanks!

**Comment by xuhang57** [comment]
I think the problem is fixed right now. It is probably caused by this:

https://github.com/pypa/setuptools/issues/1042

But yeah, close the issue now :)  Thanks for helping!
