### ISSUE TITLE
Run clank with previous release of Atmosphere/Troposphere

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#197]
I think it would be great to make clank support different atmosphere versions such as the previous release. 

For example, current the master clank would fail to deploy a `z` release atmosphere since 

https://github.com/cyverse/atmosphere/blob/master/extras/systemd/atmosphere-full.service

doesn't exist in the `z` branch of the atmosphere.

Just an idea
Thanks!

**Comment by cdosborn** [comment]
This has come up (and bitten us). I think we've decided we need this functionality, but havn't closed in on a solution or allocated time to work on it. We have thrown around some ideas. I'll enumerate them here:

**Ideas:**
1.  Tag clank, if you want to build a version of atmo/tropo you download the right version of clank. (Seems easiest/simplest to implement)
2. Clank gets built in support for installing a proper version via `--release zesty-zapdos` ex.

**Comment by xuhang57** [comment]
I will try out the `tag` clank later today and provide some feedbacks 👍  Thanks!

**Comment by cdosborn** [comment]
There are some arguments in favor of keeping clank.py as close to pure ansible. I think this really just an argument for keeping clank.py simple. I think there are some benefits of wrapping ansible in a small python script. 

Clank is a deploy tool and should be able to deploy any version of the service. In order for clank to even deploy a release it will need to be able to identify the releases (no way around tagging all the things). 

I want to flesh out idea 2 a bit more. I think we could view the clank repo as two parts: a small python wrapper and a set of ansible scripts. The python wrapper would accept a release version, and clone that version of clank in a separate folder. The python script would just defer to those playbooks. 

**Pros:**
- clank.py follows the philosophy of "just working". You don't have to go check out an older release, clank just does it for you.
- By pulling in the latest version of the python script, you are guaranteed features that you might not get when checkout older python script
**Cons:**
- Its weird that a repo clones another version of itself. This could be resolved by moving the wrapper python script into a separate repo. (which would mean that clank-ansible would be pure ansible if you wanted to use clank that way

**Comment by cdosborn** [comment]
We should probably go with the simpler approach and make something more complex when the need exists.

**Comment by xuhang57** [comment]
![screen shot 2017-07-31 at 16 42 27](https://user-images.githubusercontent.com/7245860/28827826-c85d2720-769c-11e7-9e01-f95dd61d2c8b.png)
![screen shot 2017-08-01 at 09 33 33](https://user-images.githubusercontent.com/7245860/28827827-c85dadee-769c-11e7-8b64-309f1f871561.png)
![screen shot 2017-08-01 at 09 33 43](https://user-images.githubusercontent.com/7245860/28827829-c864be36-769c-11e7-96b6-57ac51748bb6.png)
![screen shot 2017-08-01 at 09 35 09](https://user-images.githubusercontent.com/7245860/28827828-c863f960-769c-11e7-8c91-4e791a5d365e.png)

**Comment by xuhang57** [comment]
@steve-gregory So I use the tag `17-z-z-2` tag of clank to deploy atmosphere/troposphere on a Ubuntu14 server. Completed all the ansible playbooks and have no errors. But `git` seems to be confused on which branch that I am using. From the troposphere default setting, I can tell I am using the `z` version.

**Comment by xuhang57** [comment]
I don't think this is an issue now. But not sure whether it would have any impact on using atmosphere as the atmosphere/troposphere repo cannot find which is the currently working branch.
