### ISSUE TITLE
Warn/Error when New Relic is not installed/configured/working

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/clank#205]
Sometimes:

- New Relic config is not in `local.py` (Usually due to manual `./configure`)
- New Relic package is not installed in virtual environment (Rare, but has happened)
- New Relic is not pushing stats (Can happen)

Proposal: We can check for these as one of the final steps in Clank.

**Comment by cdosborn** [comment]
Was really surprised to **not** find atmo/tropo vars for new relic, we need to add those. That should satisfy the need for a clank check.
