### ISSUE TITLE
Cannot uninstall new relic

### ISSUE THREAD

**Issue by cdosborn** [cyverse/clank#222]
There is no way to uninstall new relic once installed.

**Comment by julianpistorius** [comment]
It's a feature, not a bug! ™️

**Comment by steve-gregory** [comment]
Is that something we are worried about?

I would assume that 'uninstall new relic' could consist of simply deleting the file `new_relic.py` in `atmosphere` and `troposphere`...

I guess we can make a utility playbook to "remove new relic".. but who would want to do that? 😄

**Comment by cdosborn** [comment]
"NEW_RELIC_ENABLED:..." waddup

**Comment by cdosborn** [comment]
The issue isn't so much about  installation, as much as being able to turn it off

**Comment by steve-gregory** [comment]
Does clank care about that? We don't currently have playbook(s) to _uninstall_ components of atmosphere...

The "better, ansible-istic" approach might be: 
- Destroy VM with new relic
- Re-run clank on new VM, do not configure with new relic.

**Comment by cdosborn** [comment]
Not sure if you meant to say "uninstall", because i'm not advocating for that. I just want to disable new_relic.

Someone was like "can you disable new relic. First approach (and most intuitive) rerun clank without new relic vars. welp atmosphere still use new relic. Go learn about how we enable new relic (this is what clank should shield you from having todo), and then fix server.

For refererence I coudn't nuke the server it was jtc. Just think we should make optional parts (like sentry/new relic) optional.

**Comment by julianpistorius** [comment]
Yeah - all kidding aside, Connor is right.

In New Relic's case they come after us for money if we run it on more servers than we have signed up for. In Sentry's case we pollute our production monitoring by having it enabled on dev boxes.
