### ISSUE TITLE
app-install-instance-deploy-automation role fails on remote deployment when creating hosts file

### ISSUE THREAD

**Issue by c-mart** [cyverse/clank#223]
[This](https://github.com/cyverse/clank/blob/master/roles/app-install-instance-deploy-automation/tasks/main.yml#L6) fails when deploying to a remote target with no pre-existing Ansible hosts file. Error is `fatal: [vm142-29.cyverse.org -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /opt/dev/atmosphere-ansible/ansible does not exist"}`, even though that directory does exist on the target (but not the deployment host). I think it should only be creating files on the target.

**Comment by cdosborn** [comment]
Yeah copying from the secrets repo needs to be in a local_action

**Comment by cdosborn** [comment]
I'll submit a quick pr for this.
