### ISSUE TITLE
Interactive mode for clank

### ISSUE THREAD

**Issue by steve-gregory** [cyverse/clank#40]
I was speaking with @cdosborn about an "interactive mode" for clank and he mentioned that you can use the tool `tty` to determine whether or not your input has "come from a terminal".

```
> tty
/dev/tty#
> echo "Hello world" | tty
not a tty
```

We could use this logic to set an `IS_INTERACTIVE` flag, and if _required_ variables are missing from the .yml, clank could request those values one by one:

```
Value ATMO_WORKSPACE is missing: /opt/dev/atmosphere
Value ... is missing:
```

**Comment by lenards** [comment]
It looks like python has a function on the `os` module to determine this: 

https://docs.python.org/3/library/os.html#os.isatty

It looks like that chatter on StackOverflow is that using flags from `sys` [`sys.flags.interactive`](https://docs.python.org/3/library/sys.html#sys.flags) or the `isatty()` on `sys.__stdin__` might be more reliable (so, `sys.__stdin__.isatty()`).
